=== surendragalwa11/XML/ass2.xsd
<?xml version="1.0"?>


<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xsd:element name="COMPANY" type="company"/>
<xsd:complexType name="company">
<xsd:sequence>
    <xsd:element name="EMPLOYEE" type="employee"/>
</xsd:sequence>
</xsd:complexType>

  <xsd:complexType name="employee">
    <xsd:sequence>
      
       <xsd:element name="FirstName" type="xsd:string"/> 
       <xsd:element name="lastName" type="xsd:string"/>
       <xsd:element name="ContactNo" type="xsd:string"/>
       <xsd:element name="Email" type="xsd:strng"/>
       <xsd:element name="Address" type="Address"/>
	 
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="Address">
      <xsd:sequence>
          <xsd:element name="City" type="xsd:string"/>
          <xsd:element name="State" type="xsd:string"/>
          <xsd:element name="Zip" type="xsd:integer"/>
      </xsd:sequence>
  </xsd:complexType>
  

</xsd:schema>

=== surendragalwa11/XML/ass2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<COMPANY
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='ass2.xsd'>
    <EMPLOYEE>
        <FirstName></FirstName>
        <lastName></lastName>
        <ContactNo></ContactNo>
        <Email></Email>
        <Address>
            <City></City>
            <State></State>
            <Zip></Zip>
        </Address>
    </EMPLOYEE>

</COMPANY>
